export const exampleCards = [
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/1920/1080',
    date: 'Novermber 4, 2020',
    header: "Everyone Needs a Special 'Sit Spot' in...",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me.`,
    source: `treehugger`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/400/300',
    date: 'Novermber 4, 2020',
    header: 'Nature makes you better',
    text: `We all know how good nature can make us feel. We have known it for millennia: the sound of the ocean, the scents of a forest, the ..`,
    source: `National parks Traveler`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/1920/1080',
    date: 'Novermber 4, 2020',
    header: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis eius consequatur quas recusandae! Ad?',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, quaerat ullam? Repudiandae, non. Aut quaerat ab adipisci magnam! Quibusdam totam voluptas aspernatur voluptatibus nostrum aut aliquid voluptatum repudiandae repellat reiciendis officiis et aperiam natus ipsam nesciunt vel velit, praesentium ut iste, cum porro rem voluptatem odio. Sequi soluta labore incidunt. Exercitationem, architecto doloribus eligendi officiis blanditiis, obcaecati iste omnis possimus sit repudiandae cumque. Commodi dolor reprehenderit suscipit possimus sapiente consequuntur fugiat, minus laboriosam voluptatem deleniti corporis, cupiditate iure assumenda in inventore sint illum dicta dolorum, voluptas nam fugit nostrum ut porro. Perspiciatis fugit similique veritatis aspernatur et mollitia sed exercitationem.`,
    source: `treehugger`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/400/300',
    date: 'Novermber 4, 2020',
    header: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis eius consequatur quas recusandae! Ad?',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, quaerat ullam? Repudiandae, non. Aut quaerat ab adipisci magnam! Quibusdam totam voluptas aspernatur voluptatibus nostrum aut aliquid voluptatum repudiandae repellat reiciendis officiis et aperiam natus ipsam nesciunt vel velit, praesentium ut iste, cum porro rem voluptatem odio. Sequi soluta labore incidunt. Exercitationem, architecto doloribus eligendi officiis blanditiis, obcaecati iste omnis possimus sit repudiandae cumque. Commodi dolor reprehenderit suscipit possimus sapiente consequuntur fugiat, minus laboriosam voluptatem deleniti corporis, cupiditate iure assumenda in inventore sint illum dicta dolorum, voluptas nam fugit nostrum ut porro. Perspiciatis fugit similique veritatis aspernatur et mollitia sed exercitationem.`,
    source: `treehugger`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/250/200',
    date: 'Novermber 4, 2020',
    header: 'Grand Teton Renews Historic Crest Trail',
    text: `“The linking together of the Cascade and Death Canyon trails, at their heads, took place on October...`,
    source: `National parks Traveler`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/960/640',
    date: 'Novermber 4, 2020',
    header: 'Nostalgic Photos of Tourists in U.S. Nation...',
    text: `Uri Løvevild Golman and Helle Løvevild Golman are National Geographic Explorers and...`,
    source: `treehugger`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/1080/720',
    date: 'Novermber 4, 2020',
    header: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis eius consequatur quas recusandae! Ad?',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, quaerat ullam? Repudiandae, non. Aut quaerat ab adipisci magnam! Quibusdam totam voluptas aspernatur voluptatibus nostrum aut aliquid voluptatum repudiandae repellat reiciendis officiis et aperiam natus ipsam nesciunt vel velit, praesentium ut iste, cum porro rem voluptatem odio. Sequi soluta labore incidunt. Exercitationem, architecto doloribus eligendi officiis blanditiis, obcaecati iste omnis possimus sit repudiandae cumque. Commodi dolor reprehenderit suscipit possimus sapiente consequuntur fugiat, minus laboriosam voluptatem deleniti corporis, cupiditate iure assumenda in inventore sint illum dicta dolorum, voluptas nam fugit nostrum ut porro. Perspiciatis fugit similique veritatis aspernatur et mollitia sed exercitationem.`,
    source: `treehugger`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/1920/1080',
    date: 'Novermber 4, 2020',
    header: 'Everyone',
    text: `Ever since I read Richard Louv's.`,
    source: `treehugger`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/400/300',
    date: 'Novermber 4, 2020',
    header: 'Nature makes you better',
    text: `We all know how good nature can make us feel. We have known it for millennia: the sound of the ocean, the scents of a forest, the ..`,
    source: `National parks Traveler`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/1920/1080',
    date: 'Novermber 4, 2020',
    header: "Everyone Needs a Special 'Sit Spot' in...",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me.`,
    source: `treehugger`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/400/300',
    date: 'Novermber 4, 2020',
    header: 'Nature makes you better',
    text: `We all know how good nature can make us feel. We have known it for millennia: the sound of the ocean, the scents of a forest, the ..`,
    source: `National parks Traveler`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/250/200',
    date: 'Novermber 4, 2020',
    header: 'Grand Teton Renews Historic Crest Trail',
    text: `“The linking together of the Cascade and Death Canyon trails, at their heads, took place on October...`,
    source: `National parks Traveler`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/960/640',
    date: 'Novermber 4, 2020',
    header: 'Nostalgic Photos of Tourists in U.S. Nation...',
    text: `Uri Løvevild Golman and Helle Løvevild Golman are National Geographic Explorers and...`,
    source: `treehugger`,
    link: '#',
  },
  {
    alt: 'a corgi',
    src: 'http://placekitten.com/1080/720',
    date: 'Novermber 4, 2020',
    header: "Scientists Don't Know Why Polaris Is So Weird",
    text: `Humans have long relied on the starry sky to push into new frontiers, sail to the very edge...`,
    source: `treehugger`,
    link: '#',
  },
];
